// <auto-generated />
namespace _16125296_OnlineStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ProductImages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductImages));
        
        string IMigrationMetadata.Id
        {
            get { return "201901160251126_ProductImages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
